/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsAssignmentManagementRouteImport } from './routes/projects.assignment-management'
import { Route as ProjectsDigitalWalletRouteImport } from './routes/projects.digital-wallet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAssignmentManagementRoute =
  ProjectsAssignmentManagementRouteImport.update({
    id: '/projects/assignment-management',
    path: '/projects/assignment-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsDigitalWalletRoute = ProjectsDigitalWalletRouteImport.update({
  id: '/projects/digital-wallet',
  path: '/projects/digital-wallet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/assignment-management': typeof ProjectsAssignmentManagementRoute
  '/projects/digital-wallet': typeof ProjectsDigitalWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/assignment-management': typeof ProjectsAssignmentManagementRoute
  '/projects/digital-wallet': typeof ProjectsDigitalWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/assignment-management': typeof ProjectsAssignmentManagementRoute
  '/projects/digital-wallet': typeof ProjectsDigitalWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/resume'
    | '/sitemap.xml'
    | '/projects/assignment-management'
    | '/projects/digital-wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resume'
    | '/sitemap.xml'
    | '/projects/assignment-management'
    | '/projects/digital-wallet'
  id:
    | '__root__'
    | '/'
    | '/resume'
    | '/sitemap.xml'
    | '/projects/assignment-management'
    | '/projects/digital-wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumeRoute: typeof ResumeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjectsAssignmentManagementRoute: typeof ProjectsAssignmentManagementRoute
  ProjectsDigitalWalletRoute: typeof ProjectsDigitalWalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/assignment-management': {
      id: '/projects/assignment-management'
      path: '/projects/assignment-management'
      fullPath: '/projects/assignment-management'
      preLoaderRoute: typeof ProjectsAssignmentManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/digital-wallet': {
      id: '/projects/digital-wallet'
      path: '/projects/digital-wallet'
      fullPath: '/projects/digital-wallet'
      preLoaderRoute: typeof ProjectsDigitalWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumeRoute: ResumeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjectsAssignmentManagementRoute: ProjectsAssignmentManagementRoute,
  ProjectsDigitalWalletRoute: ProjectsDigitalWalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
